### ISSUE TITLE
Скрипты перенести в отдельный файл и подключить

### ISSUE THREAD

**Issue by kyborq** [lifelsbeautiful/Groom-room#1]
1. Лучше не использовать код js в тэгах. Вместо этого создайте отдельный файл с расширением .js и подключайте его через тег
2. Тег нужно подключать в конце тега body
```html
<body>
  ...
  <script src="js/script.js"></script>
</body>
```

https://github.com/lifelsbeautiful/Groom-room/blob/586e0d3c6f3c2f9fb9da2b35b707dda5cc0caff1/Index.html#L35

**Comment by lifelsbeautiful** [comment]
Спасибо, исправлено!

**Comment by kyborq** [comment]
@lifelsbeautiful форматирование соблюдайте.
Используйте фооматтер. Для vscode есть prettier и для него можно настроить автоформатироварие
